// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolymorphicOwned.Sample;

#nullable disable

namespace PolymorphicOwned.Sample.Migrations
{
    [DbContext(typeof(AudienceDbContext))]
    partial class AudienceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("PolymorphicOwned:Mappings", "{\"mappings\":[{\"owner\":\"PolymorphicOwned.Sample.Audience, PolymorphicOwned.Sample, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null\",\"nav\":\"GraduationRule\",\"required\":true,\"discriminator\":\"graduation_rule_type\",\"subtypes\":[{\"clr\":\"PolymorphicOwned.Sample.ScoreThresholdRule, PolymorphicOwned.Sample, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null\",\"value\":\"score_threshold\",\"members\":[{\"member\":\"DemotionScore\",\"shadow\":\"DemotionScore\"},{\"member\":\"GraduationScore\",\"shadow\":\"GraduationScore\"},{\"member\":\"MinResponsesToGraduate\",\"shadow\":\"MinResponsesToGraduate\"}]},{\"clr\":\"PolymorphicOwned.Sample.TaskAccuracyRule, PolymorphicOwned.Sample, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null\",\"value\":\"task_accuracy\",\"members\":[{\"member\":\"MaxTasks\",\"shadow\":\"MaxTasks\"},{\"member\":\"MinTasks\",\"shadow\":\"MinTasks\"},{\"member\":\"TargetAccuracy\",\"shadow\":\"TargetAccuracy\"}]}]}]}")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolymorphicOwned.Sample.Audience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("DemotionScore")
                        .HasColumnType("double precision")
                        .HasColumnName("demotion_score");

                    b.Property<double?>("GraduationScore")
                        .HasColumnType("double precision")
                        .HasColumnName("graduation_score");

                    b.Property<int?>("MaxTasks")
                        .HasColumnType("integer")
                        .HasColumnName("max_tasks");

                    b.Property<int?>("MinResponsesToGraduate")
                        .HasColumnType("integer")
                        .HasColumnName("min_responses_to_graduate");

                    b.Property<int?>("MinTasks")
                        .HasColumnType("integer")
                        .HasColumnName("min_tasks");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<double?>("TargetAccuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("target_accuracy");

                    b.Property<string>("graduation_rule_type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("graduation_rule_type");

                    b.HasKey("Id")
                        .HasName("pk_audiences");

                    b.ToTable("audiences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
