// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolymorphicOwned.Sample;

#nullable disable

namespace PolymorphicOwned.Sample.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("PolymorphicOwned:Mappings", "{\"mappings\":[{\"owner\":\"PolymorphicOwned.Sample.Order, PolymorphicOwned.Sample, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null\",\"nav\":\"Discount\",\"required\":true,\"discriminator\":\"discount_type\",\"subtypes\":[{\"clr\":\"PolymorphicOwned.Sample.PercentageDiscount, PolymorphicOwned.Sample, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null\",\"value\":\"percentage\",\"members\":[{\"member\":\"MaxAmount\",\"shadow\":\"MaxAmount\"},{\"member\":\"MinItems\",\"shadow\":\"MinItems\"},{\"member\":\"Percentage\",\"shadow\":\"Percentage\"}]},{\"clr\":\"PolymorphicOwned.Sample.FixedAmountDiscount, PolymorphicOwned.Sample, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null\",\"value\":\"fixed_amount\",\"members\":[{\"member\":\"Amount\",\"shadow\":\"Amount\"},{\"member\":\"MaxRedemptions\",\"shadow\":\"MaxRedemptions\"},{\"member\":\"MinOrderTotal\",\"shadow\":\"MinOrderTotal\"}]}]}]}")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolymorphicOwned.Sample.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<double?>("MaxAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("max_amount");

                    b.Property<int?>("MaxRedemptions")
                        .HasColumnType("integer")
                        .HasColumnName("max_redemptions");

                    b.Property<int?>("MinItems")
                        .HasColumnType("integer")
                        .HasColumnName("min_items");

                    b.Property<double?>("MinOrderTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("min_order_total");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<string>("discount_type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discount_type");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
